# Define your clients here. The example below connects to database 0 of the default Redis server.
#
# See https://github.com/snc/SncRedisBundle/blob/master/docs/README.md for instructions on
# how to configure the bundle.
# https://github.com/snc/SncRedisBundle/tree/4.6.0/docs
# https://github.com/snc/SncRedisBundle/tree/5d5079c5eb9d51b0ada06c8a3ad11a13b83d70bb/docs

snc_redis:
    clients:
       default:
           type: predis
           alias: default
           dsn: "%env(REDIS_URL)%"
           logging: '%kernel.debug%'
